import type { Category, Mood, Product } from "./types";
import type { Silhouette } from "./studies";

/**
 * Catalog source of truth for this preview.
 * Names are editorial placeholders. Prices and category facts come from the
 * supplied नव GLAM catalog structure. Photography is intentionally empty so
 * real files in /public/products can replace the color studies.
 */
export const products: Product[] = [
  {
    id: "ng-01",
    name: "Nav Edit 01",
    nameIsPlaceholder: true,
    slug: "nav-edit-01",
    category: "3-piece",
    categoryLabel: "3-piece set",
    price: 4200,
    images: [],
    study: "gulnaar",
    silhouette: "set",
    description:
      "A three-piece set from the current catalog: blouse, skirt and jacket, listed together and meant to be styled as one look or taken apart.",
    catalogNotes: ["3-piece set"],
    sizes: ["Catalog size unspecified"],
    colorName: "Gulnaar",
    colorIsEditorial: true,
    tags: ["NEW"],
    keywords: ["set", "three piece", "3 piece", "new", "edit", "jacket", "skirt", "blouse"],
    collection: "The Nav Edit",
    moods: ["festive", "wedding-guest"],
    featured: true,
    pieces: ["blouse", "skirt", "jacket"],
  },
  {
    id: "ng-02",
    name: "Heritage Bloom",
    nameIsPlaceholder: true,
    slug: "heritage-bloom",
    category: "3-piece",
    categoryLabel: "3-piece set",
    price: 3800,
    images: [],
    study: "emerald",
    silhouette: "set",
    description:
      "A three-piece set from the current catalog. The editorial name is a placeholder until the catalog title is connected.",
    catalogNotes: ["3-piece set"],
    sizes: ["Catalog size unspecified"],
    colorName: "Emerald",
    colorIsEditorial: true,
    tags: ["EDITED"],
    keywords: ["set", "three piece", "heritage", "bloom", "green"],
    collection: "The Nav Edit",
    moods: ["festive", "statement"],
    featured: true,
    pieces: ["blouse", "skirt", "jacket"],
  },
  {
    id: "ng-03",
    name: "Gulnaar Set",
    nameIsPlaceholder: true,
    slug: "gulnaar-set",
    category: "3-piece",
    categoryLabel: "3-piece set",
    price: 3500,
    images: [],
    study: "rani",
    silhouette: "set",
    description:
      "A three-piece set from the current catalog, grouped here under an editorial name for the styled edit.",
    catalogNotes: ["3-piece set"],
    sizes: ["Catalog size unspecified"],
    colorName: "Rani",
    colorIsEditorial: true,
    tags: ["NEW"],
    keywords: ["set", "gulnaar", "rani", "pink", "three piece"],
    collection: "The Nav Edit",
    moods: ["party", "mehfil"],
    featured: true,
    pieces: ["blouse", "skirt", "jacket"],
  },
  {
    id: "ng-04",
    name: "Riwaayat",
    nameIsPlaceholder: true,
    slug: "riwaayat",
    category: "3-piece",
    categoryLabel: "3-piece set",
    price: 3400,
    images: [],
    study: "maroon",
    silhouette: "set",
    description:
      "A three-piece set from the current catalog. This listing is in the group that requires skirt-side stitching.",
    catalogNotes: ["3-piece set", "Skirt-side stitching required"],
    sizes: ["Catalog size unspecified"],
    colorName: "Maroon",
    colorIsEditorial: true,
    tags: ["EDITED"],
    keywords: ["set", "riwaayat", "stitching", "skirt", "three piece", "maroon"],
    collection: "The Nav Edit",
    moods: ["wedding-guest", "festive"],
    featured: false,
    pieces: ["blouse", "skirt", "jacket"],
  },
  {
    id: "ng-05",
    name: "Rang Reverie",
    nameIsPlaceholder: true,
    slug: "rang-reverie",
    category: "2-piece",
    categoryLabel: "2-piece set",
    price: 3300,
    images: [],
    study: "magenta",
    silhouette: "set2",
    description:
      "A two-piece set from the current catalog. Pair it as listed, or read the pieces as separate layers once photography and styling notes are connected.",
    catalogNotes: ["2-piece set"],
    sizes: ["Catalog size unspecified"],
    colorName: "Magenta",
    colorIsEditorial: true,
    tags: ["NEW"],
    keywords: ["set", "two piece", "2 piece", "rang", "magenta"],
    collection: "The Nav Edit",
    moods: ["party", "rang"],
    featured: true,
    pieces: ["blouse", "skirt"],
  },
  {
    id: "ng-06",
    name: "Mehfil",
    nameIsPlaceholder: true,
    slug: "mehfil",
    category: "2-piece",
    categoryLabel: "2-piece set",
    price: 3200,
    images: [],
    study: "royal",
    silhouette: "set2",
    description:
      "A two-piece set from the current catalog, placed in the Mehfil edit as a styling suggestion.",
    catalogNotes: ["2-piece set"],
    sizes: ["Catalog size unspecified"],
    colorName: "Royal",
    colorIsEditorial: true,
    tags: ["EDITED"],
    keywords: ["set", "two piece", "mehfil", "blue", "royal"],
    collection: "The Nav Edit",
    moods: ["mehfil", "wedding-guest"],
    featured: true,
    pieces: ["blouse", "skirt"],
  },
  {
    id: "ng-07",
    name: "Utsav",
    nameIsPlaceholder: true,
    slug: "utsav",
    category: "2-piece",
    categoryLabel: "2-piece set",
    price: 2800,
    images: [],
    study: "saffron",
    silhouette: "set2",
    description: "A two-piece set from the current catalog.",
    catalogNotes: ["2-piece set"],
    sizes: ["Catalog size unspecified"],
    colorName: "Saffron",
    colorIsEditorial: true,
    tags: [],
    keywords: ["set", "two piece", "utsav", "orange", "saffron", "festive"],
    collection: "The Nav Edit",
    moods: ["festive", "day-out"],
    featured: false,
    pieces: ["blouse", "skirt"],
  },
  {
    id: "ng-08",
    name: "Ivory Thread",
    nameIsPlaceholder: true,
    slug: "ivory-thread",
    category: "blouse",
    categoryLabel: "Free-size blouse",
    price: 1500,
    images: [],
    study: "ivory",
    silhouette: "blouse",
    description:
      "A free-size blouse from the current catalog. Wear it inside a set or over a skirt you already own.",
    catalogNotes: ["Free-size blouse"],
    sizes: ["Free size"],
    colorName: "Ivory",
    colorIsEditorial: true,
    tags: ["EDITED"],
    keywords: ["blouse", "free size", "ivory", "cream", "top"],
    collection: "Blouse Stories",
    moods: ["everyday", "day-out"],
    featured: true,
    pieces: ["blouse"],
  },
  {
    id: "ng-09",
    name: "Rani Free Blouse",
    nameIsPlaceholder: true,
    slug: "rani-free-blouse",
    category: "blouse",
    categoryLabel: "Free-size blouse",
    price: 1300,
    images: [],
    study: "rani",
    silhouette: "blouse",
    description: "A free-size blouse from the current catalog.",
    catalogNotes: ["Free-size blouse"],
    sizes: ["Free size"],
    colorName: "Rani",
    colorIsEditorial: true,
    tags: ["NEW"],
    keywords: ["blouse", "free size", "rani", "pink"],
    collection: "Blouse Stories",
    moods: ["party", "rang"],
    featured: false,
    pieces: ["blouse"],
  },
  {
    id: "ng-10",
    name: "Daylight",
    nameIsPlaceholder: true,
    slug: "daylight",
    category: "blouse",
    categoryLabel: "Free-size blouse",
    price: 1250,
    images: [],
    study: "cream",
    silhouette: "blouse",
    description: "A free-size blouse from the current catalog.",
    catalogNotes: ["Free-size blouse"],
    sizes: ["Free size"],
    colorName: "Cream",
    colorIsEditorial: true,
    tags: [],
    keywords: ["blouse", "free size", "day", "cream", "everyday"],
    collection: "Blouse Stories",
    moods: ["everyday", "day-out"],
    featured: false,
    pieces: ["blouse"],
  },
  {
    id: "ng-11",
    name: "Padded Edit 01",
    nameIsPlaceholder: true,
    slug: "padded-edit-01",
    category: "padded-blouse",
    categoryLabel: "Padded free-size blouse",
    price: 1500,
    images: [],
    study: "midnight",
    silhouette: "blouse",
    description: "A padded free-size blouse from the current catalog.",
    catalogNotes: ["Padded free-size blouse"],
    sizes: ["Free size"],
    colorName: "Midnight",
    colorIsEditorial: true,
    tags: ["NEW"],
    keywords: ["blouse", "padded", "free size", "midnight", "black"],
    collection: "Blouse Stories",
    moods: ["after-dark", "statement"],
    featured: true,
    pieces: ["blouse"],
  },
  {
    id: "ng-12",
    name: "Padded Edit 02",
    nameIsPlaceholder: true,
    slug: "padded-edit-02",
    category: "padded-blouse",
    categoryLabel: "Padded free-size blouse",
    price: 1300,
    images: [],
    study: "emerald",
    silhouette: "blouse",
    description: "A padded free-size blouse from the current catalog.",
    catalogNotes: ["Padded free-size blouse"],
    sizes: ["Free size"],
    colorName: "Emerald",
    colorIsEditorial: true,
    tags: [],
    keywords: ["blouse", "padded", "free size", "emerald", "green"],
    collection: "Blouse Stories",
    moods: ["festive", "mehfil"],
    featured: false,
    pieces: ["blouse"],
  },
  {
    id: "ng-13",
    name: "Midnight Muse",
    nameIsPlaceholder: true,
    slug: "midnight-muse",
    category: "jacket",
    categoryLabel: "Jacket",
    price: 3400,
    images: [],
    study: "midnight",
    silhouette: "jacket",
    description:
      "A jacket from the current catalog. The piece that turns a set toward evening without asking the silhouette to change.",
    catalogNotes: ["Jacket"],
    sizes: ["Catalog size unspecified"],
    colorName: "Midnight",
    colorIsEditorial: true,
    tags: ["EDITED"],
    keywords: ["jacket", "midnight", "muse", "layer", "evening"],
    collection: "The Jacket Edit",
    moods: ["after-dark", "midnight", "statement"],
    featured: true,
    pieces: ["jacket"],
  },
  {
    id: "ng-14",
    name: "Jacket Edit 02",
    nameIsPlaceholder: true,
    slug: "jacket-edit-02",
    category: "jacket",
    categoryLabel: "Jacket",
    price: 3200,
    images: [],
    study: "mustard",
    silhouette: "jacket",
    description: "A jacket from the current catalog.",
    catalogNotes: ["Jacket"],
    sizes: ["Catalog size unspecified"],
    colorName: "Mustard",
    colorIsEditorial: true,
    tags: ["NEW"],
    keywords: ["jacket", "mustard", "yellow", "day"],
    collection: "The Jacket Edit",
    moods: ["day-out", "statement"],
    featured: false,
    pieces: ["jacket"],
  },
  {
    id: "ng-15",
    name: "Jacket Edit 03",
    nameIsPlaceholder: true,
    slug: "jacket-edit-03",
    category: "jacket",
    categoryLabel: "Jacket",
    price: 2800,
    images: [],
    study: "ink",
    silhouette: "jacket",
    description: "A jacket from the current catalog.",
    catalogNotes: ["Jacket"],
    sizes: ["Catalog size unspecified"],
    colorName: "Charcoal",
    colorIsEditorial: true,
    tags: [],
    keywords: ["jacket", "charcoal", "black", "everyday"],
    collection: "The Jacket Edit",
    moods: ["everyday", "day-out"],
    featured: false,
    pieces: ["jacket"],
  },
  {
    id: "ng-16",
    name: "Flare Edit 01",
    nameIsPlaceholder: true,
    slug: "flare-edit-01",
    category: "flare-skirt",
    categoryLabel: "15m-flare skirt",
    price: 2800,
    images: [],
    study: "turquoise",
    silhouette: "flare",
    description: "A 15m-flare skirt piece from the current catalog.",
    catalogNotes: ["15m-flare skirt piece"],
    sizes: ["Catalog size unspecified"],
    colorName: "Turquoise",
    colorIsEditorial: true,
    tags: ["NEW"],
    keywords: ["skirt", "flare", "15m", "turquoise", "volume"],
    collection: "Skirt Culture",
    moods: ["statement", "party"],
    featured: true,
    pieces: ["skirt"],
  },
  {
    id: "ng-17",
    name: "Skirt Edit 01",
    nameIsPlaceholder: true,
    slug: "skirt-edit-01",
    category: "skirt",
    categoryLabel: "Skirt",
    price: 1500,
    images: [],
    study: "royal",
    silhouette: "skirt",
    description: "A skirt from the current catalog.",
    catalogNotes: ["Skirt"],
    sizes: ["Catalog size unspecified"],
    colorName: "Royal",
    colorIsEditorial: true,
    tags: ["EDITED"],
    keywords: ["skirt", "blue", "royal"],
    collection: "Skirt Culture",
    moods: ["festive", "mehfil"],
    featured: false,
    pieces: ["skirt"],
  },
  {
    id: "ng-18",
    name: "Skirt Only 01",
    nameIsPlaceholder: true,
    slug: "skirt-only-01",
    category: "skirt-only",
    categoryLabel: "Skirt-only piece",
    price: 1250,
    images: [],
    study: "cream",
    silhouette: "skirt",
    description: "A skirt-only piece from the current catalog.",
    catalogNotes: ["Skirt-only piece"],
    sizes: ["Catalog size unspecified"],
    colorName: "Cream",
    colorIsEditorial: true,
    tags: [],
    keywords: ["skirt", "skirt only", "cream", "separate"],
    collection: "Skirt Culture",
    moods: ["everyday", "day-out"],
    featured: false,
    pieces: ["skirt"],
  },
  {
    id: "ng-19",
    name: "Skirt Edit 02",
    nameIsPlaceholder: true,
    slug: "skirt-edit-02",
    category: "skirt",
    categoryLabel: "Skirt",
    price: 1300,
    images: [],
    study: "saffron",
    silhouette: "skirt",
    description: "A skirt from the current catalog.",
    catalogNotes: ["Skirt"],
    sizes: ["Catalog size unspecified"],
    colorName: "Saffron",
    colorIsEditorial: true,
    tags: [],
    keywords: ["skirt", "saffron", "orange"],
    collection: "Skirt Culture",
    moods: ["day-out", "rang"],
    featured: false,
    pieces: ["skirt"],
  },
];

export const categoryGroups: Record<
  "sets" | "blouses" | "jackets" | "skirts",
  { label: string; categories: Category[] }
> = {
  sets: { label: "Sets", categories: ["3-piece", "2-piece"] },
  blouses: { label: "Blouses", categories: ["blouse", "padded-blouse"] },
  jackets: { label: "Jackets", categories: ["jacket"] },
  skirts: { label: "Skirts", categories: ["skirt", "skirt-only", "flare-skirt"] },
};

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}

export function getByCategory(categories: Category[]) {
  return products.filter((product) => categories.includes(product.category));
}

export function getFeatured() {
  return products.filter((product) => product.featured);
}

export function getByMood(mood: Mood) {
  return products.filter((product) => product.moods.includes(mood));
}

export function getByPiece(piece: Product["pieces"][number]) {
  return products.filter(
    (product) => product.pieces.length === 1 && product.pieces[0] === piece,
  );
}

export function getRelated(product: Product, limit = 4) {
  return products
    .filter((item) => item.slug !== product.slug && item.category === product.category)
    .concat(products.filter((item) => item.slug !== product.slug && item.collection === product.collection))
    .filter((item, index, array) => array.findIndex((entry) => entry.slug === item.slug) === index)
    .slice(0, limit);
}

export function searchProducts(query: string) {
  const needle = query.trim().toLowerCase();
  if (!needle) return [];
  return products.filter((product) => {
    const haystack = [
      product.name,
      product.categoryLabel,
      product.colorName,
      product.collection,
      product.description,
      ...product.keywords,
      ...product.moods,
      ...product.catalogNotes,
      ...product.tags,
    ]
      .join(" ")
      .toLowerCase();
    return haystack.includes(needle);
  });
}

export function silhouetteFor(category: Category): Silhouette {
  switch (category) {
    case "blouse":
    case "padded-blouse":
      return "blouse";
    case "jacket":
      return "jacket";
    case "flare-skirt":
      return "flare";
    case "2-piece":
      return "set2";
    case "3-piece":
      return "set";
    default:
      return "skirt";
  }
}
