import type { Category, Mood, Product } from "./types";
import type { Silhouette } from "./studies";

/**
 * House catalog. Photography is the cloth itself, placed in /public/products.
 * Prices stay inside the supplied नव GLAM list (₹1,250–₹4,200).
 */
export const products: Product[] = [
  {
    id: "ng-01",
    name: "Neel Mandala",
    nameIsPlaceholder: false,
    slug: "neel-mandala",
    category: "3-piece",
    categoryLabel: "Lehenga set",
    price: 4200,
    images: ["/products/neel-mandala.jpg"],
    study: "royal",
    silhouette: "set",
    description:
      "A circular lehenga in navy, rust and black, printed with medallions and a border of elephants and birds. The set includes the choli and a matching dupatta.",
    catalogNotes: ["Choli, lehenga and dupatta", "Printed border"],
    sizes: ["Catalog size unspecified"],
    colorName: "Navy",
    colorIsEditorial: false,
    tags: ["NEW"],
    keywords: ["set", "lehenga", "dupatta", "navy", "elephant", "mandala", "neel"],
    collection: "The Nav Edit",
    moods: ["festive", "mehfil", "wedding-guest"],
    featured: true,
    pieces: ["blouse", "skirt"],
  },
  {
    id: "ng-02",
    name: "Nritya",
    nameIsPlaceholder: false,
    slug: "nritya",
    category: "3-piece",
    categoryLabel: "Lehenga set",
    price: 3800,
    images: ["/products/nritya.jpg"],
    study: "midnight",
    silhouette: "set",
    description:
      "A dark-ground lehenga scattered with dancers in pink, saffron and teal, finished with a geometric hem. Worn with the long-sleeve choli and dupatta.",
    catalogNotes: ["Choli, lehenga and dupatta"],
    sizes: ["Catalog size unspecified"],
    colorName: "Ink",
    colorIsEditorial: false,
    tags: ["EDITED"],
    keywords: ["set", "lehenga", "dance", "nritya", "black", "dupatta"],
    collection: "The Nav Edit",
    moods: ["festive", "party", "statement"],
    featured: true,
    pieces: ["blouse", "skirt"],
  },
  {
    id: "ng-03",
    name: "Ajrakh Lehenga",
    nameIsPlaceholder: false,
    slug: "ajrakh-lehenga",
    category: "3-piece",
    categoryLabel: "Lehenga set",
    price: 3500,
    images: ["/products/ajrakh-lehenga.jpg"],
    study: "maroon",
    silhouette: "set",
    description:
      "Block print in black, rust and ivory — paisley, elephant and lattice bands running the full flare, with the printed choli.",
    catalogNotes: ["Choli and lehenga", "Block print"],
    sizes: ["Catalog size unspecified"],
    colorName: "Rust",
    colorIsEditorial: false,
    tags: ["NEW"],
    keywords: ["set", "lehenga", "ajrakh", "block print", "elephant", "maroon"],
    collection: "The Nav Edit",
    moods: ["wedding-guest", "festive", "mehfil"],
    featured: true,
    pieces: ["blouse", "skirt"],
  },
  {
    id: "ng-04",
    name: "Safed Kadhai",
    nameIsPlaceholder: false,
    slug: "safed-kadhai",
    category: "3-piece",
    categoryLabel: "Lehenga set",
    price: 3400,
    images: ["/products/safed-kadhai.jpg"],
    study: "ivory",
    silhouette: "set",
    description:
      "An ivory lehenga with a wide border of floral panels, gold edging and mirror flashes. The short choli repeats the same border.",
    catalogNotes: ["Choli and lehenga", "Mirror border"],
    sizes: ["Catalog size unspecified"],
    colorName: "Ivory",
    colorIsEditorial: false,
    tags: ["EDITED"],
    keywords: ["set", "lehenga", "ivory", "white", "mirror", "kadhai", "embroidered"],
    collection: "The Nav Edit",
    moods: ["wedding-guest", "mehfil", "festive"],
    featured: true,
    pieces: ["blouse", "skirt"],
  },
  {
    id: "ng-05",
    name: "Laal Chowk",
    nameIsPlaceholder: false,
    slug: "laal-chowk",
    category: "2-piece",
    categoryLabel: "2-piece set",
    price: 3300,
    images: ["/products/laal-chowk.jpg"],
    study: "rani",
    silhouette: "set2",
    description:
      "Crimson and black, with dotted panels beside paisley borders. Choli, lehenga and a red dupatta, photographed together.",
    catalogNotes: ["Choli, lehenga and dupatta"],
    sizes: ["Catalog size unspecified"],
    colorName: "Crimson",
    colorIsEditorial: false,
    tags: ["NEW"],
    keywords: ["set", "lehenga", "red", "black", "dupatta", "laal", "bandhani"],
    collection: "The Nav Edit",
    moods: ["party", "rang", "after-dark"],
    featured: true,
    pieces: ["blouse", "skirt"],
  },
  {
    id: "ng-06",
    name: "Rang Mahal",
    nameIsPlaceholder: false,
    slug: "rang-mahal",
    category: "2-piece",
    categoryLabel: "Styled set",
    price: 3200,
    images: ["/products/rang-mahal.jpg"],
    study: "saffron",
    silhouette: "set2",
    description:
      "A flared lehenga in red, yellow and royal blue panels, with a worked hem and a hot-pink dupatta. Photographed as worn.",
    catalogNotes: ["Shown as worn", "Choli, lehenga and dupatta"],
    sizes: ["Catalog size unspecified"],
    colorName: "Multicolour",
    colorIsEditorial: false,
    tags: ["EDITED"],
    keywords: ["set", "lehenga", "worn", "colour", "pink", "yellow", "blue", "festive"],
    collection: "The Nav Edit",
    moods: ["party", "rang", "statement", "festive"],
    featured: true,
    pieces: ["blouse", "skirt"],
  },
  {
    id: "ng-07",
    name: "Gol Buta",
    nameIsPlaceholder: false,
    slug: "gol-buta",
    category: "2-piece",
    categoryLabel: "Styled set",
    price: 2800,
    images: ["/products/gol-buta.jpg"],
    study: "royal",
    silhouette: "set2",
    description:
      "Navy lehenga with large folk-art rounds and an ivory hem of small figures. Worn with the printed choli and an ivory dupatta.",
    catalogNotes: ["Shown as worn", "Choli, lehenga and dupatta"],
    sizes: ["Catalog size unspecified"],
    colorName: "Navy",
    colorIsEditorial: false,
    tags: [],
    keywords: ["set", "lehenga", "navy", "circles", "folk", "dupatta", "gol"],
    collection: "The Nav Edit",
    moods: ["mehfil", "wedding-guest", "festive"],
    featured: true,
    pieces: ["blouse", "skirt"],
  },
  {
    id: "ng-08",
    name: "Ivory Paisley",
    nameIsPlaceholder: false,
    slug: "ivory-paisley",
    category: "blouse",
    categoryLabel: "Free-size blouse",
    price: 1500,
    images: ["/products/ivory-paisley.jpg"],
    study: "ivory",
    silhouette: "blouse",
    description: "A free-size strappy blouse in ivory, covered in multicolour paisley embroidery. Wear it inside a set or on its own.",
    catalogNotes: ["Free-size blouse", "Paisley embroidery"],
    sizes: ["Free size"],
    colorName: "Ivory",
    colorIsEditorial: false,
    tags: ["EDITED"],
    keywords: ["blouse", "free size", "ivory", "paisley", "embroidery", "strappy"],
    collection: "Blouse Stories",
    moods: ["everyday", "day-out"],
    featured: true,
    pieces: ["blouse"],
  },
  {
    id: "ng-09",
    name: "Rani Paisley",
    nameIsPlaceholder: false,
    slug: "rani-paisley",
    category: "blouse",
    categoryLabel: "Free-size blouse",
    price: 1300,
    images: ["/products/rani-paisley.jpg"],
    study: "rani",
    silhouette: "blouse",
    description: "The same paisley hand, on a rani ground. Free size, strappy, cropped.",
    catalogNotes: ["Free-size blouse", "Paisley embroidery"],
    sizes: ["Free size"],
    colorName: "Rani",
    colorIsEditorial: false,
    tags: ["NEW"],
    keywords: ["blouse", "free size", "rani", "pink", "paisley", "embroidery"],
    collection: "Blouse Stories",
    moods: ["party", "rang"],
    featured: false,
    pieces: ["blouse"],
  },
  {
    id: "ng-10",
    name: "Jamuni Paisley",
    nameIsPlaceholder: false,
    slug: "jamuni-paisley",
    category: "blouse",
    categoryLabel: "Free-size blouse",
    price: 1250,
    images: ["/products/jamuni-paisley.jpg"],
    study: "magenta",
    silhouette: "blouse",
    description: "Paisley embroidery on jamuni purple. A free-size strappy blouse.",
    catalogNotes: ["Free-size blouse", "Paisley embroidery"],
    sizes: ["Free size"],
    colorName: "Jamuni",
    colorIsEditorial: false,
    tags: [],
    keywords: ["blouse", "free size", "purple", "jamuni", "paisley", "embroidery"],
    collection: "Blouse Stories",
    moods: ["mehfil", "festive"],
    featured: false,
    pieces: ["blouse"],
  },
  {
    id: "ng-11",
    name: "Neel Sheesha",
    nameIsPlaceholder: false,
    slug: "neel-sheesha",
    category: "padded-blouse",
    categoryLabel: "Mirror-work blouse",
    price: 1500,
    images: ["/products/neel-sheesha.jpg"],
    study: "royal",
    silhouette: "blouse",
    description:
      "A royal-blue choli with a deep neck, tie closure and a border of mirrors set in yellow, pink, green and red.",
    catalogNotes: ["Mirror work", "Tie neck"],
    sizes: ["Free size"],
    colorName: "Royal blue",
    colorIsEditorial: false,
    tags: ["NEW"],
    keywords: ["blouse", "mirror", "sheesha", "blue", "choli", "tie"],
    collection: "Blouse Stories",
    moods: ["statement", "mehfil", "festive"],
    featured: true,
    pieces: ["blouse"],
  },
  {
    id: "ng-12",
    name: "Hari Chakra",
    nameIsPlaceholder: false,
    slug: "hari-chakra",
    category: "padded-blouse",
    categoryLabel: "Embroidered blouse",
    price: 1300,
    images: ["/products/hari-chakra.jpg"],
    study: "emerald",
    silhouette: "blouse",
    description: "Forest green blouse. Coloured ring embroidery along the hem and at the straps.",
    catalogNotes: ["Ring embroidery"],
    sizes: ["Free size"],
    colorName: "Forest",
    colorIsEditorial: false,
    tags: [],
    keywords: ["blouse", "green", "embroidery", "rings", "strappy"],
    collection: "Blouse Stories",
    moods: ["everyday", "day-out"],
    featured: false,
    pieces: ["blouse"],
  },
  {
    id: "ng-13",
    name: "Kaali Paisley",
    nameIsPlaceholder: false,
    slug: "kaali-paisley",
    category: "blouse",
    categoryLabel: "Free-size blouse",
    price: 1500,
    images: ["/products/kaali-paisley.jpg"],
    study: "midnight",
    silhouette: "blouse",
    description: "Paisley embroidery on black. A free-size strappy blouse for later hours.",
    catalogNotes: ["Free-size blouse", "Paisley embroidery"],
    sizes: ["Free size"],
    colorName: "Black",
    colorIsEditorial: false,
    tags: ["NEW"],
    keywords: ["blouse", "black", "paisley", "free size", "evening"],
    collection: "Blouse Stories",
    moods: ["after-dark", "midnight", "party"],
    featured: true,
    pieces: ["blouse"],
  },
  {
    id: "ng-14",
    name: "Hathi Mor",
    nameIsPlaceholder: false,
    slug: "hathi-mor",
    category: "jacket",
    categoryLabel: "Jacket",
    price: 3400,
    images: ["/products/hathi-mor.jpg"],
    study: "royal",
    silhouette: "jacket",
    description:
      "A sleeveless jacket in royal blue, embroidered with pink elephants, peacocks, flowers and trailing vines. The layer that turns a skirt into evening.",
    catalogNotes: ["Embroidered jacket", "Sleeveless"],
    sizes: ["Catalog size unspecified"],
    colorName: "Royal blue",
    colorIsEditorial: false,
    tags: ["EDITED"],
    keywords: ["jacket", "koti", "elephant", "peacock", "blue", "embroidery", "vest"],
    collection: "The Jacket Edit",
    moods: ["statement", "after-dark", "festive"],
    featured: true,
    pieces: ["jacket"],
  },
  {
    id: "ng-15",
    name: "Rang Rail",
    nameIsPlaceholder: false,
    slug: "rang-rail",
    category: "flare-skirt",
    categoryLabel: "Flare skirt",
    price: 2800,
    images: ["/products/rang-rail.jpg"],
    study: "mustard",
    silhouette: "flare",
    description:
      "A flared skirt in vertical bands of lime, rust, sand, ivory, mustard and blue, with fine metallic stripes near the hem.",
    catalogNotes: ["Flare skirt", "Colour-block"],
    sizes: ["Catalog size unspecified"],
    colorName: "Multicolour",
    colorIsEditorial: false,
    tags: ["NEW"],
    keywords: ["skirt", "flare", "stripes", "colour block", "mustard", "volume"],
    collection: "Skirt Culture",
    moods: ["rang", "day-out", "statement"],
    featured: true,
    pieces: ["skirt"],
  },
  {
    id: "ng-16",
    name: "Neel Resham",
    nameIsPlaceholder: false,
    slug: "neel-resham",
    category: "skirt",
    categoryLabel: "Skirt",
    price: 1500,
    images: ["/products/neel-resham.jpg"],
    study: "midnight",
    silhouette: "skirt",
    description: "Navy skirt with gold linear embroidery running through the flare and a denser band at the hem.",
    catalogNotes: ["Gold linear embroidery"],
    sizes: ["Catalog size unspecified"],
    colorName: "Navy",
    colorIsEditorial: false,
    tags: ["EDITED"],
    keywords: ["skirt", "navy", "gold", "embroidery", "resham"],
    collection: "Skirt Culture",
    moods: ["mehfil", "festive", "midnight"],
    featured: false,
    pieces: ["skirt"],
  },
  {
    id: "ng-17",
    name: "Ivory Jaal",
    nameIsPlaceholder: false,
    slug: "ivory-jaal",
    category: "skirt-only",
    categoryLabel: "Border skirt",
    price: 1250,
    images: ["/products/ivory-jaal.jpg"],
    study: "cream",
    silhouette: "skirt",
    description: "An ivory flare with a deep maroon border of floral jaal and a white tassel edge.",
    catalogNotes: ["Maroon border", "Tassel hem"],
    sizes: ["Catalog size unspecified"],
    colorName: "Ivory",
    colorIsEditorial: false,
    tags: [],
    keywords: ["skirt", "ivory", "white", "maroon", "border", "jaal"],
    collection: "Skirt Culture",
    moods: ["everyday", "wedding-guest", "day-out"],
    featured: false,
    pieces: ["skirt"],
  },
  {
    id: "ng-18",
    name: "Kaali Katha",
    nameIsPlaceholder: false,
    slug: "kaali-katha",
    category: "skirt",
    categoryLabel: "Skirt",
    price: 1300,
    images: ["/products/kaali-katha.jpg"],
    study: "ink",
    silhouette: "skirt",
    description: "A black flared skirt with a red border of repeating figures and a narrow black fringe.",
    catalogNotes: ["Figure border", "Fringe hem"],
    sizes: ["Catalog size unspecified"],
    colorName: "Black",
    colorIsEditorial: false,
    tags: [],
    keywords: ["skirt", "black", "red", "border", "fringe", "print"],
    collection: "Skirt Culture",
    moods: ["after-dark", "midnight"],
    featured: false,
    pieces: ["skirt"],
  },
];

export const categoryGroups: Record<
  "sets" | "blouses" | "jackets" | "skirts",
  { label: string; categories: Category[] }
> = {
  sets: { label: "Sets", categories: ["3-piece", "2-piece"] },
  blouses: { label: "Blouses", categories: ["blouse", "padded-blouse"] },
  jackets: { label: "Jackets", categories: ["jacket"] },
  skirts: { label: "Skirts", categories: ["skirt", "skirt-only", "flare-skirt"] },
};

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}

export function getByCategory(categories: Category[]) {
  return products.filter((product) => categories.includes(product.category));
}

export function getFeatured() {
  return products.filter((product) => product.featured);
}

export function getByMood(mood: Mood) {
  return products.filter((product) => product.moods.includes(mood));
}

export function getByPiece(piece: Product["pieces"][number]) {
  return products.filter(
    (product) => product.pieces.length === 1 && product.pieces[0] === piece,
  );
}

export function getRelated(product: Product, limit = 4) {
  return products
    .filter((item) => item.slug !== product.slug && item.category === product.category)
    .concat(products.filter((item) => item.slug !== product.slug && item.collection === product.collection))
    .filter((item, index, array) => array.findIndex((entry) => entry.slug === item.slug) === index)
    .slice(0, limit);
}

export function searchProducts(query: string) {
  const needle = query.trim().toLowerCase();
  if (!needle) return [];
  return products.filter((product) => {
    const haystack = [
      product.name,
      product.categoryLabel,
      product.colorName,
      product.collection,
      product.description,
      ...product.keywords,
      ...product.moods,
      ...product.catalogNotes,
      ...product.tags,
    ]
      .join(" ")
      .toLowerCase();
    return haystack.includes(needle);
  });
}

export function silhouetteFor(category: Category): Silhouette {
  switch (category) {
    case "blouse":
    case "padded-blouse":
      return "blouse";
    case "jacket":
      return "jacket";
    case "flare-skirt":
      return "flare";
    case "2-piece":
      return "set2";
    case "3-piece":
      return "set";
    default:
      return "skirt";
  }
}
